require('dotenv').config();
const express = require('express');
const session = require('express-session');
const path = require('path');
const authRoutes = require('./routes/auth');
const app = express();
const PORT = process.env.PORT || 3000;
const isProduction = process.env.NODE_ENV === 'production';
if (isProduction) app.set('trust proxy', 1);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(session({ secret: process.env.SESSION_SECRET || 'change-this-secret-in-production', resave: false, saveUninitialized: false, cookie: { httpOnly: true, secure: isProduction, sameSite: 'lax', maxAge: 1000 * 60 * 60 * 2 } }));
app.use(express.static(path.join(__dirname, 'public')));
app.use('/api/auth', authRoutes);
app.use('/api/byte', require('./routes/byte-routes'));
app.use('/api/faq', require('./routes/faq-routes'));
app.use('/api/userdata', require('./routes/userdata-routes'));
function requireAuth(req, res, next) { if (req.session && req.session.userId) return next(); return res.status(401).json({ error: 'Not authenticated' }); }
app.get('/api/dashboard-data', requireAuth, (req, res) => res.json({ message: `Welcome back, ${req.session.username}!` }));
app.use(require('./chat-routes'));
app.listen(PORT, () => console.log(`ByteSoft server running at http://localhost:${PORT}`));
